ALTER TABLE proxies ADD COLUMN cache_ttl INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proxies ADD COLUMN rate_limit_req INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proxies ADD COLUMN rate_limit_window INTEGER NOT NULL DEFAULT 60;

DROP TABLE IF EXISTS cache_rules;
DROP TABLE IF EXISTS rate_limits;
